/* Generated by AN DISI Unibo */ 
package it.unibo.lucciola1

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Lucciola1 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		var Period = 5000L
			  var LastFlash = java.time.Instant.now()
			  var Phase = Period 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						LastFlash = java.time.Instant.now() 
						Phase -= java.util.Random().nextLong() % Period 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", Phase )  //OCT2023
					}	 	 
					 transition(edgeName="t05",targetState="flash",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("flash") { //this:State
					action { //it:State
						LastFlash = java.time.Instant.now() 
						var NowStr = "'" + LastFlash.toString() + "'" 
						Phase = Period 
						CommUtils.outyellow("$name | Flash")
						emit("flash", "flash($NowStr)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", Phase )  //OCT2023
					}	 	 
					 transition(edgeName="t06",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t07",targetState="onFlash",cond=whenEvent("flash"))
				}	 
				state("onFlash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("flash(Time)"), Term.createTerm("flash(Time)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								val dt = java.time.Duration.between(LastFlash, java.time.Instant.now()).toMillis() 
								Phase -= dt 
								LastFlash = java.time.Instant.now() 
								val Adjust = (0.5 * Period * (1 - dt.toDouble() / Period).toDouble()).toLong() 
								if( Phase < Period / 2 
								 ){Phase -= Adjust 
								}
								else
								 {Phase += Adjust 
								 }
								Phase = if (Phase < 0) 0L else Phase 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_onFlash", 
				 	 					  scope, context!!, "local_tout_"+name+"_onFlash", Phase )  //OCT2023
					}	 	 
					 transition(edgeName="t08",targetState="flash",cond=whenTimeout("local_tout_"+name+"_onFlash"))   
					transition(edgeName="t09",targetState="onFlash",cond=whenEvent("flash"))
				}	 
			}
		}
} 
