/* Generated by AN DISI Unibo */ 
package it.unibo.fireflysystem

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Fireflysystem ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="onObstacleClose",cond=whenEvent("obstacleClose"))
					transition(edgeName="t06",targetState="onObstacleFar",cond=whenEvent("obstacleFar"))
				}	 
				state("onObstacleClose") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("obstacleClose(Distance)"), Term.createTerm("obstacleClose(Distance)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								emit("changeMode", "changeMode(synchronized,1500)" ) 
								CommUtils.outgreen("Setting system in synchronized mode")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="onObstacleClose",cond=whenEvent("obstacleClose"))
					transition(edgeName="t08",targetState="onObstacleFar",cond=whenEvent("obstacleFar"))
				}	 
				state("onObstacleFar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("obstacleFar(Distance)"), Term.createTerm("obstacleFar(Distance)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								emit("changeMode", "changeMode(random,0)" ) 
								CommUtils.outgreen("Setting system in random mode")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="onObstacleClose",cond=whenEvent("obstacleClose"))
					transition(edgeName="t010",targetState="onObstacleFar",cond=whenEvent("obstacleFar"))
				}	 
			}
		}
} 
