/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		var Period = 0L
			  var Phase = 0L 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						Period = java.lang.Math.abs(java.util.Random().nextLong() % 5000L) 
						Phase = java.lang.Math.abs(java.util.Random().nextLong() % Period) 
						CommUtils.outblack("$name | New period: $Period, initial phase: $Phase")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", Phase )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="flash",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("flash") { //this:State
					action { //it:State
						Phase = Period 
						CommUtils.outyellow("$name | Flash")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", Phase )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t02",targetState="onChangeMode",cond=whenEvent("changeMode"))
				}	 
				state("onChangeMode") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("changeMode(Mode,NewPeriod)"), Term.createTerm("changeMode(Mode,NewPeriod)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								val newMode = payloadArg(0) 
								val newPeriod = java.lang.Long.parseLong(payloadArg(1)) 
								if( newMode.equals("synchronized") 
								 ){Period = newPeriod 
								Phase = Period 
								}
								if( newMode.equals("random") 
								 ){Period = java.lang.Math.abs(java.util.Random().nextLong() % 5000L) 
								Phase = java.lang.Math.abs(java.util.Random().nextLong() % Period) 
								}
								CommUtils.outred("$name | New period: $Period, initial phase: $Phase")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_onChangeMode", 
				 	 					  scope, context!!, "local_tout_"+name+"_onChangeMode", Phase )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="flash",cond=whenTimeout("local_tout_"+name+"_onChangeMode"))   
					transition(edgeName="t04",targetState="onChangeMode",cond=whenEvent("changeMode"))
				}	 
			}
		}
} 
